# Generated by Django 4.2.3 on 2023-07-19 01:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppNotas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Bodega',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Editorial',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Informe',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('descripcion', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='ProductoTipo',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=16)),
                ('email', models.CharField(max_length=255)),
                ('contraseña', models.CharField(max_length=32)),
                ('fecha_creacion', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ProductoEditorial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('editorial_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='AppNotas.editorial')),
                ('producto_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='AppNotas.producto')),
            ],
        ),
        migrations.CreateModel(
            name='ProductoAutor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='AppNotas.autor')),
                ('producto_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='AppNotas.producto')),
            ],
        ),
        migrations.AddField(
            model_name='producto',
            name='producto_tipo_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='AppNotas.productotipo'),
        ),
        migrations.CreateModel(
            name='InformeInventario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('informe_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='AppNotas.informe')),
                ('producto_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='AppNotas.producto')),
            ],
        ),
        migrations.AddField(
            model_name='informe',
            name='autor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='AppNotas.usuario'),
        ),
        migrations.AddField(
            model_name='informe',
            name='destino_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='destino_id', to='AppNotas.bodega'),
        ),
        migrations.AddField(
            model_name='informe',
            name='origen_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='origen_id', to='AppNotas.bodega'),
        ),
        migrations.CreateModel(
            name='BodegaInventario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('bodega_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='AppNotas.bodega')),
                ('producto_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='AppNotas.producto')),
            ],
        ),
    ]
